# Generated by Django 4.2.4 on 2023-09-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webBlogs', '0002_webblogs_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='webblogs',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webblogs',
            name='linkTeaser',
            field=models.CharField(default='ไม่มี URL', max_length=2000),
        ),
        migrations.AlterField(
            model_name='webblogs',
            name='link',
            field=models.CharField(default='ไม่มี URL', max_length=2000),
        ),
    ]
