# Generated by Django 4.2.4 on 2023-09-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webBlogs', '0003_webblogs_likes_webblogs_linkteaser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webblogs',
            name='likes',
        ),
    ]
