# Generated by Django 4.2.4 on 2023-10-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webBlogs', '0008_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='userName',
        ),
    ]
